#pragma once

#define BASE_ERROR_VALUE -1

typedef enum
{
    STATUS_SUCCESS = 0,

    STATUS_FAILURE        = BASE_ERROR_VALUE - 0,
    STATUS_INVALID_ARG    = BASE_ERROR_VALUE - 1,
    STATUS_ALLOC_FAILED   = BASE_ERROR_VALUE - 2,
    STATUS_DEALLOC_FAILED = BASE_ERROR_VALUE - 3,
    STATUS_NO_SPACE       = BASE_ERROR_VALUE - 4,
} eSTATUS;

typedef void* (*fGENERIC_ALLOCATOR) (size_t);
typedef void (*fGENERIC_DEALLOCATOR) (void*);